// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudget.Data;

#nullable disable

namespace MyBudget.Data.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260927191929_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MyBudget.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRainyDayFund")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumBalance")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferCadence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "AsOf")
                        .IsUnique();

                    b.ToTable("AccountBalances");
                });

            modelBuilder.Entity("MyBudget.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("MyBudget.Domain.AssetValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "AsOf")
                        .IsUnique();

                    b.ToTable("AssetValue");
                });

            modelBuilder.Entity("MyBudget.Domain.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AnchorDueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BankAutopayDiscount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DueDay")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundingAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutopay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCardEligible")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LabelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProjectedAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FundingAccountId");

                    b.HasIndex("LabelId");

                    b.HasIndex("PaymentAccountId");

                    b.HasIndex("PaymentCardId");

                    b.ToTable("BudgetLines");
                });

            modelBuilder.Entity("MyBudget.Domain.BudgetPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ActualAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ProjectedAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId", "Period")
                        .IsUnique();

                    b.ToTable("BudgetPeriods");
                });

            modelBuilder.Entity("MyBudget.Domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualFee")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AnnualFeeMonth")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Apr")
                        .HasPrecision(6, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("DueDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoyaltyProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PayingAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PointValueCents")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PromoApr")
                        .HasPrecision(6, 3)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PromoAprExpires")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatementDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyProgramId");

                    b.HasIndex("PayingAccountId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MyBudget.Domain.CardBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "AsOf")
                        .IsUnique();

                    b.ToTable("CardBalances");
                });

            modelBuilder.Entity("MyBudget.Domain.CardPerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardPerk");
                });

            modelBuilder.Entity("MyBudget.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCardEligible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyBudget.Domain.CategoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LabelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MarkAsTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Match")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LabelId");

                    b.ToTable("CategoryRules");
                });

            modelBuilder.Entity("MyBudget.Domain.ContributionLimits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HsaCatchUp")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HsaFamily")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HsaSelfOnly")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ira")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IraCatchUp")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Retirement401kCatchUp")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Retirement401kEmployee")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Retirement401kTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("ContributionLimits");
                });

            modelBuilder.Entity("MyBudget.Domain.DeductionElection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountPerCheck")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PercentOfGross")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<int>("Treatment")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId");

                    b.ToTable("DeductionElections");
                });

            modelBuilder.Entity("MyBudget.Domain.DividendPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reinvested")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SharesHeld")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId", "ExDate")
                        .IsUnique();

                    b.ToTable("Dividends");
                });

            modelBuilder.Entity("MyBudget.Domain.EarnRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AnnualSpendCap")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LabelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsPerDollar")
                        .HasPrecision(8, 3)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LabelId");

                    b.ToTable("EarnRules");
                });

            modelBuilder.Entity("MyBudget.Domain.EstimatedTaxPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jurisdiction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EstimatedTaxPayments");
                });

            modelBuilder.Entity("MyBudget.Domain.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountIds")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LowerIsBetter")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ManualCurrent")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Metric")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("StartValue")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MyBudget.Domain.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Drip")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Ticker")
                        .IsUnique();

                    b.ToTable("Holdings");
                });

            modelBuilder.Entity("MyBudget.Domain.HsaContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HsaYearId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HsaYearId");

                    b.ToTable("HsaContribution");
                });

            modelBuilder.Entity("MyBudget.Domain.HsaMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HsaYearId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HsaYearId", "Month")
                        .IsUnique();

                    b.ToTable("HsaMonth");
                });

            modelBuilder.Entity("MyBudget.Domain.HsaYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CatchUpEligible")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LimitOverrideFamily")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LimitOverrideSelfOnly")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TargetAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("HsaYears");
                });

            modelBuilder.Entity("MyBudget.Domain.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FirstDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CardId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("MyBudget.Domain.IncomeReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId");

                    b.ToTable("IncomeReceipts");
                });

            modelBuilder.Entity("MyBudget.Domain.IncomeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IncomeSources");
                });

            modelBuilder.Entity("MyBudget.Domain.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("MyBudget.Domain.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExtraMonthlyPayment")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalPrincipal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ScheduledPayment")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TermMonths")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BudgetLineId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("MyBudget.Domain.LoanBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoanId", "AsOf")
                        .IsUnique();

                    b.ToTable("LoanBalance");
                });

            modelBuilder.Entity("MyBudget.Domain.LoyaltyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentTier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointValueCents")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PointsBalance")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetTier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoyaltyPrograms");
                });

            modelBuilder.Entity("MyBudget.Domain.LoyaltyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProgramSpend")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QualifyingPoints")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId", "Year")
                        .IsUnique();

                    b.ToTable("LoyaltyProgress");
                });

            modelBuilder.Entity("MyBudget.Domain.LoyaltyTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Benefits")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("LoyaltyTier");
                });

            modelBuilder.Entity("MyBudget.Domain.Obligation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndPeriod")
                        .HasColumnType("TEXT");

                    b.Property<int>("EveryMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MonthlyAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ShareOfLine")
                        .HasPrecision(6, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartPeriod")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("PersonId");

                    b.ToTable("Obligation");
                });

            modelBuilder.Entity("MyBudget.Domain.PaySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AnchorPayDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstPayDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PayOnPriorBusinessDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondPayDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("PaySchedules");
                });

            modelBuilder.Entity("MyBudget.Domain.Paycheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gross")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Net")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId", "PayDate", "Kind")
                        .IsUnique();

                    b.ToTable("Paychecks");
                });

            modelBuilder.Entity("MyBudget.Domain.PaycheckLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaycheckId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaycheckId");

                    b.ToTable("PaycheckLine");
                });

            modelBuilder.Entity("MyBudget.Domain.PaycheckOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GrossAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossFraction")
                        .HasPrecision(6, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PayDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProrateFixedDeductions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId", "PayDate")
                        .IsUnique();

                    b.ToTable("PaycheckOverride");
                });

            modelBuilder.Entity("MyBudget.Domain.PaymentAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Period")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentAllocation");
                });

            modelBuilder.Entity("MyBudget.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MyBudget.Domain.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "Date")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("MyBudget.Domain.ReceivableCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ReceivableCharge");
                });

            modelBuilder.Entity("MyBudget.Domain.ReceivablePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("ReceivablePayments");
                });

            modelBuilder.Entity("MyBudget.Domain.SalaryRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AnnualAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("SalaryRates");
                });

            modelBuilder.Entity("MyBudget.Domain.SpendThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TierName")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValueDollars")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("SpendThresholds");
                });

            modelBuilder.Entity("MyBudget.Domain.StatusPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgramId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ProgramId");

                    b.ToTable("StatusPath");
                });

            modelBuilder.Entity("MyBudget.Domain.TaxBracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FilingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jurisdiction")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Over")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxYearId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxYearId");

                    b.ToTable("TaxBracket");
                });

            modelBuilder.Entity("MyBudget.Domain.TaxYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalMedicareRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdditionalMedicareThreshold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FederalStandardDeductionHeadOfHousehold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FederalStandardDeductionMarriedJointly")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FederalStandardDeductionSingle")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LtcgThreshold15HeadOfHousehold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LtcgThreshold15MarriedJointly")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LtcgThreshold15Single")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LtcgThreshold20HeadOfHousehold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LtcgThreshold20MarriedJointly")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LtcgThreshold20Single")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MedicareRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MissouriStandardDeductionHeadOfHousehold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MissouriStandardDeductionMarriedOneIncome")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MissouriStandardDeductionMarriedSpouseWorks")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MissouriStandardDeductionSingle")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MissouriSupplementalRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SocialSecurityRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SocialSecurityWageBase")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SupplementalHighRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SupplementalHighThreshold")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SupplementalRate")
                        .HasPrecision(8, 5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("TaxYears");
                });

            modelBuilder.Entity("MyBudget.Domain.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DividendPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fees")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("HoldingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DividendPaymentId");

                    b.HasIndex("HoldingId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("MyBudget.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BudgetLineId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CounterpartyAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManuallyCategorized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LabelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Merchant")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceivablePaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReconciledWithId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("CardId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CounterpartyAccountId");

                    b.HasIndex("Date");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("LabelId");

                    b.HasIndex("ReceivablePaymentId");

                    b.HasIndex("ReconciledWithId");

                    b.HasIndex("AccountId", "CardId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("MyBudget.Domain.WithholdingElection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Deductions")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DependentCredits")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExtraWithholding")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("FederalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MissouriExtraWithholding")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MissouriStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MultipleJobs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OtherIncome")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("WithholdingElections");
                });

            modelBuilder.Entity("MyBudget.Domain.AccountBalance", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany("Balances")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyBudget.Domain.AssetValue", b =>
                {
                    b.HasOne("MyBudget.Domain.Asset", "Asset")
                        .WithMany("Values")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("MyBudget.Domain.BudgetLine", b =>
                {
                    b.HasOne("MyBudget.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Account", "FundingAccount")
                        .WithMany()
                        .HasForeignKey("FundingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyBudget.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Account", "PaymentAccount")
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyBudget.Domain.Card", "PaymentCard")
                        .WithMany()
                        .HasForeignKey("PaymentCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("FundingAccount");

                    b.Navigation("Label");

                    b.Navigation("PaymentAccount");

                    b.Navigation("PaymentCard");
                });

            modelBuilder.Entity("MyBudget.Domain.BudgetPeriod", b =>
                {
                    b.HasOne("MyBudget.Domain.BudgetLine", "BudgetLine")
                        .WithMany("Periods")
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("MyBudget.Domain.Card", b =>
                {
                    b.HasOne("MyBudget.Domain.LoyaltyProgram", "LoyaltyProgram")
                        .WithMany()
                        .HasForeignKey("LoyaltyProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Account", "PayingAccount")
                        .WithMany()
                        .HasForeignKey("PayingAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LoyaltyProgram");

                    b.Navigation("PayingAccount");
                });

            modelBuilder.Entity("MyBudget.Domain.CardBalance", b =>
                {
                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany("Balances")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MyBudget.Domain.CardPerk", b =>
                {
                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany("Perks")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MyBudget.Domain.CategoryRule", b =>
                {
                    b.HasOne("MyBudget.Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyBudget.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyBudget.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BudgetLine");

                    b.Navigation("Category");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("MyBudget.Domain.DeductionElection", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany("Deductions")
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.DividendPayment", b =>
                {
                    b.HasOne("MyBudget.Domain.Holding", "Holding")
                        .WithMany("Dividends")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("MyBudget.Domain.EarnRule", b =>
                {
                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany("EarnRules")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyBudget.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyBudget.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Card");

                    b.Navigation("Category");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("MyBudget.Domain.Holding", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyBudget.Domain.HsaContribution", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.HsaYear", "HsaYear")
                        .WithMany("Contributions")
                        .HasForeignKey("HsaYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("HsaYear");
                });

            modelBuilder.Entity("MyBudget.Domain.HsaMonth", b =>
                {
                    b.HasOne("MyBudget.Domain.HsaYear", "HsaYear")
                        .WithMany("Months")
                        .HasForeignKey("HsaYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HsaYear");
                });

            modelBuilder.Entity("MyBudget.Domain.ImportBatch", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MyBudget.Domain.IncomeReceipt", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.Label", b =>
                {
                    b.HasOne("MyBudget.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyBudget.Domain.Loan", b =>
                {
                    b.HasOne("MyBudget.Domain.Asset", "Asset")
                        .WithMany("Loans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asset");

                    b.Navigation("BudgetLine");
                });

            modelBuilder.Entity("MyBudget.Domain.LoanBalance", b =>
                {
                    b.HasOne("MyBudget.Domain.Loan", "Loan")
                        .WithMany("Balances")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("MyBudget.Domain.LoyaltyProgress", b =>
                {
                    b.HasOne("MyBudget.Domain.LoyaltyProgram", "Program")
                        .WithMany("Progress")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("MyBudget.Domain.LoyaltyTier", b =>
                {
                    b.HasOne("MyBudget.Domain.LoyaltyProgram", "Program")
                        .WithMany("Tiers")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("MyBudget.Domain.Obligation", b =>
                {
                    b.HasOne("MyBudget.Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Person", "Person")
                        .WithMany("Obligations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyBudget.Domain.PaySchedule", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany("PaySchedules")
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.Paycheck", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany()
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.PaycheckLine", b =>
                {
                    b.HasOne("MyBudget.Domain.Paycheck", "Paycheck")
                        .WithMany("Lines")
                        .HasForeignKey("PaycheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paycheck");
                });

            modelBuilder.Entity("MyBudget.Domain.PaycheckOverride", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany("Overrides")
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.PaymentAllocation", b =>
                {
                    b.HasOne("MyBudget.Domain.ReceivablePayment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MyBudget.Domain.ReceivableCharge", b =>
                {
                    b.HasOne("MyBudget.Domain.Person", "Person")
                        .WithMany("Charges")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyBudget.Domain.ReceivablePayment", b =>
                {
                    b.HasOne("MyBudget.Domain.Person", "Person")
                        .WithMany("Payments")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyBudget.Domain.SalaryRate", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany("SalaryRates")
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.SpendThreshold", b =>
                {
                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany("Thresholds")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MyBudget.Domain.StatusPath", b =>
                {
                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.LoyaltyProgram", "Program")
                        .WithMany("Paths")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("MyBudget.Domain.TaxBracket", b =>
                {
                    b.HasOne("MyBudget.Domain.TaxYear", "TaxYear")
                        .WithMany("Brackets")
                        .HasForeignKey("TaxYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxYear");
                });

            modelBuilder.Entity("MyBudget.Domain.Trade", b =>
                {
                    b.HasOne("MyBudget.Domain.DividendPayment", "DividendPayment")
                        .WithMany()
                        .HasForeignKey("DividendPaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Holding", "Holding")
                        .WithMany("Trades")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DividendPayment");

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("MyBudget.Domain.Transaction", b =>
                {
                    b.HasOne("MyBudget.Domain.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyBudget.Domain.BudgetLine", "BudgetLine")
                        .WithMany()
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyBudget.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Account", "CounterpartyAccount")
                        .WithMany()
                        .HasForeignKey("CounterpartyAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.ReceivablePayment", "ReceivablePayment")
                        .WithMany()
                        .HasForeignKey("ReceivablePaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyBudget.Domain.Transaction", "ReconciledWith")
                        .WithMany()
                        .HasForeignKey("ReconciledWithId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("BudgetLine");

                    b.Navigation("Card");

                    b.Navigation("Category");

                    b.Navigation("CounterpartyAccount");

                    b.Navigation("ImportBatch");

                    b.Navigation("Label");

                    b.Navigation("ReceivablePayment");

                    b.Navigation("ReconciledWith");
                });

            modelBuilder.Entity("MyBudget.Domain.WithholdingElection", b =>
                {
                    b.HasOne("MyBudget.Domain.IncomeSource", "IncomeSource")
                        .WithMany("Withholdings")
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("MyBudget.Domain.Account", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyBudget.Domain.Asset", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("MyBudget.Domain.BudgetLine", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("MyBudget.Domain.Card", b =>
                {
                    b.Navigation("Balances");

                    b.Navigation("EarnRules");

                    b.Navigation("Perks");

                    b.Navigation("Thresholds");
                });

            modelBuilder.Entity("MyBudget.Domain.Holding", b =>
                {
                    b.Navigation("Dividends");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("MyBudget.Domain.HsaYear", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Months");
                });

            modelBuilder.Entity("MyBudget.Domain.IncomeSource", b =>
                {
                    b.Navigation("Deductions");

                    b.Navigation("Overrides");

                    b.Navigation("PaySchedules");

                    b.Navigation("SalaryRates");

                    b.Navigation("Withholdings");
                });

            modelBuilder.Entity("MyBudget.Domain.Loan", b =>
                {
                    b.Navigation("Balances");
                });

            modelBuilder.Entity("MyBudget.Domain.LoyaltyProgram", b =>
                {
                    b.Navigation("Paths");

                    b.Navigation("Progress");

                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("MyBudget.Domain.Paycheck", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MyBudget.Domain.Person", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Obligations");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("MyBudget.Domain.ReceivablePayment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("MyBudget.Domain.TaxYear", b =>
                {
                    b.Navigation("Brackets");
                });
#pragma warning restore 612, 618
        }
    }
}
