<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MyBudget.Engines.Ledger/MyBudget.Engines.Ledger.csproj" />
    <ProjectReference Include="../../src/MyBudget.Engines.Paycheck/MyBudget.Engines.Paycheck.csproj" />
    <ProjectReference Include="../../src/MyBudget.Engines.Hsa/MyBudget.Engines.Hsa.csproj" />
    <ProjectReference Include="../../src/MyBudget.Engines.Amortization/MyBudget.Engines.Amortization.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
</Project>
